In [5]:
# 1. Import numpy as np and see the version
#     Q. Import numpy as np and print the version number.

import numpy as np
print(np.__version__)

1.18.4


In [6]:
# 2. How to create a 1D array?
#     Q. Create a 1D array of numbers from 0 to 9


a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.arange(10)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
# 3. How to create a boolean array?
#     Q. Create a 3×3 numpy array of all True’s


c = np.full((3, 3,), True, dtype=bool)
d = np.ones((3, 3), dtype=bool)

print(c)
print()
print(d)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [8]:
# 4. How to extract items that satisfy a given condition from 1D array?
#     Q. Extract all odd numbers from arr

e = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  # input
e = e[e % 2 == 1]

print(e)

[1 3 5 7 9]


In [9]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
#     Q. Replace all odd numbers in arr with -1


f = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
f[f % 2 == 1] = -1

print(f)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [10]:
# 6. How to replace items that satisfy a condition without affecting the original array?
#     Q. Replace all odd numbers in arr with -1 without changing arr


g = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
g_2 = g
g_2 = np.where(g_2 % 2 == 1,-1, g_2)

print(g)
print(g_2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [11]:
# 7. How to reshape an array?
#      Q. Convert a 1D array to a 2D array with 2 rows

h = np.arange(10).reshape(2, -1)
h


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [17]:
# 8. How to stack two arrays vertically?
#     Q. Stack arrays a and b vertically

i = np.arange(10).reshape(2,-1)
j = np.repeat(1, 10).reshape(2,-1)

np.concatenate([i, j], axis=0)
np.vstack([i, j])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
# 9. How to stack two arrays horizontally?
#     Q. Stack the arrays a and b horizontally.

k = np.arange(10).reshape(2,-1)
l = np.repeat(1, 10).reshape(2,-1)

np.concatenate([k, l], axis=1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [35]:
# 10. How to generate custom sequences in numpy without hardcoding?
#     Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
m = np.array([1,2,3])

np.concatenate([np.repeat(m, 3), np.tile(m, 3)])
# np.r_[np.repeat(a, 3), np.tile(a, 3)] - IDK kow its work



array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [39]:
# 11. How to get the common items between two python numpy arrays?
#     Q. Get the common items between a and b

n = np.array([1,2,3,2,3,4,3,4,5,6])
o= np.array([7,2,10,2,7,4,9,4,9,8,])

np.intersect1d(n,o)



array([2, 4])

In [41]:

prstuwxyz

NameError: name 'prstuwxyz' is not defined

In [42]:
# 12. How to remove from one array those items that exist in another?
#     Q. From array a remove all items present in array b



In [44]:
# 13. How to get the positions where elements of two arrays match?
#     Q. Get the positions where elements of a and b match



In [45]:
# 14. How to extract all numbers between a given range from a numpy array?
#         a = np.array([2, 6, 1, 9, 10, 3, 27])


In [46]:
# 15. How to make a python function that handles scalars to work on numpy arrays?
#     Q. Convert the function maxx that works on two scalars, to work on two arrays.



In [47]:
# 16. How to swap two columns in a 2d numpy array?
#     Q. Swap columns 1 and 2 in the array arr.



In [ ]:
# 17. How to swap two rows in a 2d numpy array?
#     Q. Swap rows 1 and 2 in the array arr:

