In [6]:
# 1. Import numpy as np and see the version
import numpy as np
print(np.__version__)

1.18.4


In [8]:
# 2. How to create a 1D array?
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.arange(10)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [14]:
# 3. How to create a boolean array?
c = np.full((3, 3,), True, dtype=bool)
d = np.ones((3, 3), dtype=bool)

print(c)
print()
print(d)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [13]:
# 4. How to extract items that satisfy a given condition from 1D array?
e = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  # input
e = e[e % 2 == 1]

print(e)

[1 3 5 7 9]


In [16]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
f = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
f[f % 2 == 1] = -1

print(f)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
