In [4]:
# 1. Import numpy as np and see the version
#     Q. Import numpy as np and print the version number.

import numpy as np
print(np.__version__)

1.18.4


In [5]:
# 2. How to create a 1D array?
#     Q. Create a 1D array of numbers from 0 to 9


a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.arange(10)

print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
# 3. How to create a boolean array?
#     Q. Create a 3×3 numpy array of all True’s


c = np.full((3, 3,), True, dtype=bool)
d = np.ones((3, 3), dtype=bool)

print(c)
print()
print(d)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [7]:
# 4. How to extract items that satisfy a given condition from 1D array?
#     Q. Extract all odd numbers from arr

e = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])  # input
e = e[e % 2 == 1]

print(e)

[1 3 5 7 9]


In [8]:
# 5. How to replace items that satisfy a condition with another value in numpy array?
#     Q. Replace all odd numbers in arr with -1


f = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
f[f % 2 == 1] = -1

print(f)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [20]:
# 6. How to replace items that satisfy a condition without affecting the original array?
#     Q. Replace all odd numbers in arr with -1 without changing arr


g = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
g_2 = g
g_2 = np.where(g_2 % 2 == 1,-1, g_2)

print(g)
print(g_2)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [43]:
# 7. How to reshape an array?
#      Q. Convert a 1D array to a 2D array with 2 rows

h = np.arange(10).reshape(2, -1)
h


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [53]:
# 8. How to stack two arrays vertically?
#     Q. Stack arrays a and b vertically

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=0)
np.vstack([a, b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [51]:
# 9. How to stack two arrays horizontally?
#     Q. Stack the arrays a and b horizontally.

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concatenate([a, b], axis=1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [58]:
# 10. How to generate custom sequences in numpy without hardcoding?
#     Q. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
a = np.array([1,2,3])
